// <auto-generated />
namespace PiProject.data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class mm : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mm));
        
        string IMigrationMetadata.Id
        {
            get { return "201911280959506_mm"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
